version: 2.1

jobs:
  build-test:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start Application
          command: npm run start &
      - run:
          name: Wait for App to be Ready
          command: |
            set +e
            timeout 10 bash -c "until curl -s http://localhost:3000 > /dev/null; do echo 'Waiting for app...'; sleep 1; done"
            echo "Finished waiting"
            set -e
      - run:
          name: Run Cypress Tests
          command: npx cypress run

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test
