version: 2.1

jobs:
  # Job to build and start the app
  build-and-start-app:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            ls
      - run:
          name: Start Application
          command: |
            cd CypressTestReactfrontendWithCircleCI
            npm start &
          background: true
      - run:
          name: Wait for Application to Start
          command: |
            # Wait until the application is accessible (replace with actual endpoint)
            while ! curl -s http://localhost:3000 > /dev/null; do sleep 1; done
          timeout: 180

  # Job to run Cypress tests
  run-cypress-tests:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - run:
          name: Install Dependencies for Tests
          command: |
            cd CypressTestReactfrontendWithCircleCI
            npm install
      - run:
          name: Run Cypress Tests
          command: |
            cd CypressTestReactfrontendWithCircleCI
            npm run cypress:run

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-start-app
      - run-cypress-tests:
          requires:
            - build-and-start-app
